/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class AAssignStmt extends PStmt
{
    private PVarExp _l_;
    private TColonEquals _colonEquals_;
    private PExp _r_;

    public AAssignStmt()
    {
        // Constructor
    }

    public AAssignStmt(
        @SuppressWarnings("hiding") PVarExp _l_,
        @SuppressWarnings("hiding") TColonEquals _colonEquals_,
        @SuppressWarnings("hiding") PExp _r_)
    {
        // Constructor
        setL(_l_);

        setColonEquals(_colonEquals_);

        setR(_r_);

    }

    @Override
    public Object clone()
    {
        return new AAssignStmt(
            cloneNode(this._l_),
            cloneNode(this._colonEquals_),
            cloneNode(this._r_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignStmt(this);
    }

    public PVarExp getL()
    {
        return this._l_;
    }

    public void setL(PVarExp node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TColonEquals getColonEquals()
    {
        return this._colonEquals_;
    }

    public void setColonEquals(TColonEquals node)
    {
        if(this._colonEquals_ != null)
        {
            this._colonEquals_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colonEquals_ = node;
    }

    public PExp getR()
    {
        return this._r_;
    }

    public void setR(PExp node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._l_)
            + toString(this._colonEquals_)
            + toString(this._r_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._colonEquals_ == child)
        {
            this._colonEquals_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._l_ == oldChild)
        {
            setL((PVarExp) newChild);
            return;
        }

        if(this._colonEquals_ == oldChild)
        {
            setColonEquals((TColonEquals) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
