/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class AGeqRelExp extends PRelExp
{
    private PIntExp _left_;
    private TGeq _geq_;
    private PIntExp _right_;

    public AGeqRelExp()
    {
        // Constructor
    }

    public AGeqRelExp(
        @SuppressWarnings("hiding") PIntExp _left_,
        @SuppressWarnings("hiding") TGeq _geq_,
        @SuppressWarnings("hiding") PIntExp _right_)
    {
        // Constructor
        setLeft(_left_);

        setGeq(_geq_);

        setRight(_right_);

    }

    @Override
    public Object clone()
    {
        return new AGeqRelExp(
            cloneNode(this._left_),
            cloneNode(this._geq_),
            cloneNode(this._right_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGeqRelExp(this);
    }

    public PIntExp getLeft()
    {
        return this._left_;
    }

    public void setLeft(PIntExp node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TGeq getGeq()
    {
        return this._geq_;
    }

    public void setGeq(TGeq node)
    {
        if(this._geq_ != null)
        {
            this._geq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._geq_ = node;
    }

    public PIntExp getRight()
    {
        return this._right_;
    }

    public void setRight(PIntExp node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._left_)
            + toString(this._geq_)
            + toString(this._right_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._geq_ == child)
        {
            this._geq_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._left_ == oldChild)
        {
            setLeft((PIntExp) newChild);
            return;
        }

        if(this._geq_ == oldChild)
        {
            setGeq((TGeq) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PIntExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
