/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class ANoneArgList extends PArgList
{

    public ANoneArgList()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ANoneArgList();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANoneArgList(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
