/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class ANotNotExp extends PNotExp
{
    private TBang _bang_;
    private PNotExp _arg_;

    public ANotNotExp()
    {
        // Constructor
    }

    public ANotNotExp(
        @SuppressWarnings("hiding") TBang _bang_,
        @SuppressWarnings("hiding") PNotExp _arg_)
    {
        // Constructor
        setBang(_bang_);

        setArg(_arg_);

    }

    @Override
    public Object clone()
    {
        return new ANotNotExp(
            cloneNode(this._bang_),
            cloneNode(this._arg_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotNotExp(this);
    }

    public TBang getBang()
    {
        return this._bang_;
    }

    public void setBang(TBang node)
    {
        if(this._bang_ != null)
        {
            this._bang_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._bang_ = node;
    }

    public PNotExp getArg()
    {
        return this._arg_;
    }

    public void setArg(PNotExp node)
    {
        if(this._arg_ != null)
        {
            this._arg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arg_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._bang_)
            + toString(this._arg_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._bang_ == child)
        {
            this._bang_ = null;
            return;
        }

        if(this._arg_ == child)
        {
            this._arg_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._bang_ == oldChild)
        {
            setBang((TBang) newChild);
            return;
        }

        if(this._arg_ == oldChild)
        {
            setArg((PNotExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
