/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class ASomeParamListTail extends PParamListTail
{
    private TComma _comma_;
    private PDecl _decl_;
    private PParamListTail _paramListTail_;

    public ASomeParamListTail()
    {
        // Constructor
    }

    public ASomeParamListTail(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PDecl _decl_,
        @SuppressWarnings("hiding") PParamListTail _paramListTail_)
    {
        // Constructor
        setComma(_comma_);

        setDecl(_decl_);

        setParamListTail(_paramListTail_);

    }

    @Override
    public Object clone()
    {
        return new ASomeParamListTail(
            cloneNode(this._comma_),
            cloneNode(this._decl_),
            cloneNode(this._paramListTail_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomeParamListTail(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PDecl getDecl()
    {
        return this._decl_;
    }

    public void setDecl(PDecl node)
    {
        if(this._decl_ != null)
        {
            this._decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decl_ = node;
    }

    public PParamListTail getParamListTail()
    {
        return this._paramListTail_;
    }

    public void setParamListTail(PParamListTail node)
    {
        if(this._paramListTail_ != null)
        {
            this._paramListTail_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramListTail_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._decl_)
            + toString(this._paramListTail_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._decl_ == child)
        {
            this._decl_ = null;
            return;
        }

        if(this._paramListTail_ == child)
        {
            this._paramListTail_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._decl_ == oldChild)
        {
            setDecl((PDecl) newChild);
            return;
        }

        if(this._paramListTail_ == oldChild)
        {
            setParamListTail((PParamListTail) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
