/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class ASomeDeclsDeclsStmts extends PDeclsStmts
{
    private PDecl _decl_;
    private PDeclsStmts _declsStmts_;

    public ASomeDeclsDeclsStmts()
    {
        // Constructor
    }

    public ASomeDeclsDeclsStmts(
        @SuppressWarnings("hiding") PDecl _decl_,
        @SuppressWarnings("hiding") PDeclsStmts _declsStmts_)
    {
        // Constructor
        setDecl(_decl_);

        setDeclsStmts(_declsStmts_);

    }

    @Override
    public Object clone()
    {
        return new ASomeDeclsDeclsStmts(
            cloneNode(this._decl_),
            cloneNode(this._declsStmts_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASomeDeclsDeclsStmts(this);
    }

    public PDecl getDecl()
    {
        return this._decl_;
    }

    public void setDecl(PDecl node)
    {
        if(this._decl_ != null)
        {
            this._decl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decl_ = node;
    }

    public PDeclsStmts getDeclsStmts()
    {
        return this._declsStmts_;
    }

    public void setDeclsStmts(PDeclsStmts node)
    {
        if(this._declsStmts_ != null)
        {
            this._declsStmts_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declsStmts_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decl_)
            + toString(this._declsStmts_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decl_ == child)
        {
            this._decl_ = null;
            return;
        }

        if(this._declsStmts_ == child)
        {
            this._declsStmts_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decl_ == oldChild)
        {
            setDecl((PDecl) newChild);
            return;
        }

        if(this._declsStmts_ == oldChild)
        {
            setDeclsStmts((PDeclsStmts) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
