/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class AVarPrimeExp extends PPrimeExp
{
    private PVarExp _varExp_;

    public AVarPrimeExp()
    {
        // Constructor
    }

    public AVarPrimeExp(
        @SuppressWarnings("hiding") PVarExp _varExp_)
    {
        // Constructor
        setVarExp(_varExp_);

    }

    @Override
    public Object clone()
    {
        return new AVarPrimeExp(
            cloneNode(this._varExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarPrimeExp(this);
    }

    public PVarExp getVarExp()
    {
        return this._varExp_;
    }

    public void setVarExp(PVarExp node)
    {
        if(this._varExp_ != null)
        {
            this._varExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varExp_ == child)
        {
            this._varExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varExp_ == oldChild)
        {
            setVarExp((PVarExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
