/* This file was generated by SableCC (http://www.sablecc.org/). */

package malgol.node;

import malgol.analysis.*;

@SuppressWarnings("nls")
public final class TArrayOf extends Token
{
    public TArrayOf()
    {
        super.setText("arrayof");
    }

    public TArrayOf(int line, int pos)
    {
        super.setText("arrayof");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArrayOf(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArrayOf(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArrayOf text.");
    }
}
